plugins {
    id 'com.android.application'
}

android {
    namespace 'com.solwash.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.solwash.app"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.0.1"
    }

    signingConfigs {
        release {
            storeFile file('../solwash-release.jks')
            storePassword 'SolWash@2026'
            keyAlias 'solwash'
            keyPassword 'SolWash@2026'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
}
